### ISSUE TITLE
feature request: Sign in with apple/google

### ISSUE THREAD

**Issue by JaFu-py** [revoltchat/legal#7] opened 2022-08-19 16:28 UTC
### What do you want to see?

Please add a sign in with apple and/or google. makes sign up and login WAY faster. Thxbai

**Comment by Rexogamer** [comment] 2022-08-19 16:33
...of all the repositories-

Duplicate of revoltchat/backend#127.

**Comment by insertish** [comment] 2023-01-26 20:14
Superseded by https://github.com/authifier/authifier/issues/35.

**Closed by insertish** 2023-01-26 20:14 UTC
Labels: enhancement
